(define a (read))
(define b (read))
(define c (read))
(cond ((not (= (+ a b c) 180))
       (display "Error\n"))
      ((and (= a 60)
            (= b 60)
            (= c 60)
        (display "Equilateral\n")))
      ((or (= a b)
           (= a c)
           (= b c))
       (display "Isosceles\n"))
      ((and (not (= a b))
            (not (= a c))
            (not (= b c)))
       (display "Scalene\n")))
