(display "NFC West       W   L  T\n")
(display "-----------------------\n")
(display "Seattle        13  3  0\n")
(display "San Francisco  12  4  0\n")
(display "Arizona        10  6  0\n")
(display "St. Louis      7   9  0\n")
(display "\n")
(display "NFC North      W   L  T\n")
(display "-----------------------\n")
(display "Green Bay      8   7  1\n")
(display "Chicago        8   8  0\n")
(display "Detroit        7   9  0\n")
(display "Minnesota      5  10  1\n")
