(define a (read))
(define b (read))
(define c (read))
(display (modulo (+ a b) c))
(newline)
(display (modulo (+ (modulo a c)
                    (modulo b c)) c))
(newline)
(display (modulo (* a b) c))
(newline)
(display (modulo (* (modulo a c) (modulo b c)) c))
(newline)
