(define n (read))
(define (iter n)
  (if (> n 0)
    (begin (print-odd?)
           (iter (- n 1)))))
(define (print-odd?)
  (define x (read))
  (display x)
  (display " is")
  (if (even? x)
    (display " even\n")
    (display " odd\n")))
(iter n)
