(define count (read))
(define checklist '())
(define (iter n l)
  (if (< n count)
    (iter (+ n 1) (set-val l))
    l))
(define (set-val l)
  (define k (read))
  (if (= k 0)
      (cdr l)
      (cons k l)))
(define (sum n acc l)
  (if (< n (vector-length l))
    (sum (+ n 1)
         (+ acc (vector-ref l n)) l)
    acc))
(display (sum 0 0 (list->vector (iter 0 '()))))
(newline)
