(define ball-vector (make-vector 101 0))
(define n (read))
(define m (read))
(define (vector-init count)
  (if (< count 101)
    (begin (vector-set! ball-vector count count)
           (vector-init (+ count 1)))))
(vector-init 1)

(define (put-iter count)
  (define (ball-insert)
    (define from (read))
    (define to (read))
    (define (iter from to)
      (define temp (vector-ref ball-vector from))
      (vector-set! ball-vector from (vector-ref ball-vector to))
      (vector-set! ball-vector to temp))
    (iter from to))
  (if (< count m)
    (begin (ball-insert)
           (put-iter (+ 1 count)))
    (print-vector 1)))

(define (print-vector count)
  (if (<= count n)
    (begin (display (vector-ref ball-vector count))
           (display " ")
           (print-vector (+ count 1)))
    (newline)))
(put-iter 0)
