(define minv 1000000)
(define maxv -1000000)
(define (iter n)
  (if (> n 0)
    (begin (setv)
           (iter (- n 1)))))
(define (setv)
  (define v (read))
  (set! minv (min minv v))
  (set! maxv (max maxv v)))
(iter (read))
(display minv)
(display " ")
(print maxv)
