(define count (read))
(define (add-read)
  (define a (read))
  (define b (read))
  (display a)
  (display " + ")
  (display b)
  (display " = ")
  (display (+ a b))(newline))
(define (iter n)
  (if (> n 0)
   (begin (display "Case #")
          (display (- count n -1))
          (display ": ")
          (add-read)
          (iter (- n 1)))))
(iter count)
