(define count (read))
(define (add-read)
  (display (+ (read) (read)))(newline))
(define (iter n)
  (if (> n 0)
   (begin (display "Case #")
          (display (- count n -1))
          (display ": ")
          (add-read)
          (iter (- n 1)))))
(iter count)
