(define dp-vector (make-vector 10 1))
(define (sum v count acc)
  (if (> count 9)
    (print (modulo acc 10007))
    (sum v (+ count 1) (+ acc (vector-ref v count)))))
(define (iter n)
  (if (> n 0)
    (begin (dp-step 1)
           (iter (- n 1)))))
(define (dp-step n)
  (if (< n 10)
    (begin (vector-set! dp-vector n (+ (vector-ref dp-vector n)
                                       (vector-ref dp-vector (- n 1))))
           (dp-step (+ n 1)))))
(iter (- (read) 1))
(sum dp-vector 0 0)
