(import (chicken io))
(define (reverse-string s)
  (print (list->string (reverse (string->list s)))))
(define (iter)
  (let ((a (read-line)))
    (if (not (equal? "END" a))
      (begin (reverse-string a)
             (iter)))))
(iter)
