(define a (read))
(define b (read))
(define c (read))
(define d (read))
(define e (read))
(display (min (lcm a b c)
              (lcm a b d)
              (lcm a b e)
              (lcm a c d)
              (lcm a c e)
              (lcm a d e)
              (lcm b c d)
              (lcm b c e)
              (lcm b d e)
              (lcm c d e)))
(newline)
