(define count (read))
(define number (read))
(define (sum-number count acc number)
  (cond ((= count 0)
         acc)
        (else (sum-number (- count 1)
                          (+ acc (modulo number 10))
                          (quotient number 10)))))
(display (sum-number count 0 number))
(newline)
