(define (iter)
  (define n (read))
  (define rev-n (string->number (list->string (reverse (string->list (number->string n))))))
  (define (pallendrom)
    (if (= n rev-n)
      (display "yes\n")
      (display "no\n")))
  (cond ((not (= n 0))
         (pallendrom)
         (iter))))
(iter)
