(do ((n (read) (- n 1))
     (y 0 y)
     (m 0 m))
  ((= n 0)
   (cond ((< y m) (print "Y " y))
         ((> y m) (print "M " m))
         (else (print "Y M " y))))
  (let ((t (read)))
    (set! y (+ y (* 10 (+ 1 (quotient t 30)))))
    (set! m (+ m (* 15 (+ 1 (quotient t 60)))))))
