(define dp-vector (make-vector 1000002 0))
(vector-set! dp-vector 0 1)
(vector-set! dp-vector 1 3)
(define (iter n)
  (if (< n 1000002)
    (begin (vector-set! dp-vector n (modulo (+ (* 2 (vector-ref dp-vector (- n 1)))
                                               (vector-ref dp-vector (- n 2)))
                                            9901))
           (iter (+ n 1)))))
(iter 2)
(print (vector-ref dp-vector (read)))
