(let ((a (read))
      (b (read))
      (c (read)))
  (if (or (= (+ a b) c)
          (= (+ a c) b)
          (= (+ c b) a)
          (= a b)
          (= a c)
          (= c b))
    (print "S")
    (print "N")))
