(define dp-vector (make-vector 36 0))
(vector-set! dp-vector 0 1)
(define (set-val index from to)
  (if (>= from 0)
    (begin (vector-set! dp-vector index (+ (vector-ref dp-vector index)
                                           (* (vector-ref dp-vector from)
                                              (vector-ref dp-vector to))))
           (set-val index (- from 1) (+ to 1)))))

(define (iter count)
  (if (< count 36)
    (begin (set-val count (- count 1) 0)
           (iter (+ count 1)))))
(iter 1)
(print (vector-ref dp-vector (read)))
