(define x1 (read))
(define y1 (read))
(define x2 (read))
(define y2 (read))
(define x3 (read))
(define y3 (read))
(define x4 (read))
(define y4 (read))
(define l (max (- (max x2 x4) (min x1 x3))
            (- (max y2 y4) (min y1 y3))))
(display (* l l))
(newline)
