(define fib-vector (make-vector 117 0))
(vector-set! fib-vector 1 1)
(vector-set! fib-vector 2 1)
(vector-set! fib-vector 3 1)
(define (iter count)
  (if (< count 117)
    (begin (vector-set! fib-vector count (+ (vector-ref fib-vector (- count 1))
                                            (vector-ref fib-vector (- count 3))))
           (iter (+ count 1)))))
(iter 4)
(print (vector-ref fib-vector (read)))
