(define dp (make-vector 1000010 0))
(vector-set! dp 2 1)
(vector-set! dp 3 1)

(define (init-dp count)
  (cond ((<= count 1000003)
         (cond ((= (modulo count 3) (modulo count 2) 0)
                (vector-set! dp count (+ 1 (min (vector-ref dp (- count 1))
                                                (vector-ref dp (quotient count 2))
                                                (vector-ref dp (quotient count 3))))))
               ((= (modulo count 3) 0)
                (vector-set! dp count (+ 1 (min (vector-ref dp (- count 1))
                                                (vector-ref dp (quotient count 3))))))
               ((= (modulo count 2) 0)
                (vector-set! dp count (+ 1 (min (vector-ref dp (- count 1))
                                                (vector-ref dp (quotient count 2))))))
               (else (vector-set! dp count (+ 1 (vector-ref dp (- count 1))))))
         (init-dp (+ count 1)))
        (else (display (vector-ref dp (read)))
              (newline))))
(init-dp 4)
