(define x (read))
(define y (read))
(cond
  ((and (< x 0) (< y 0))
   (display "3")
   (newline))
  ((and (< x 0) (> y 0))
   (display "2")
   (newline))
  ((and (> x 0) (< y 0))
   (display "4")
   (newline))
  (else (display "1")
        (newline)))
