(let ((x (read))
      (y (read))
      (n (read)))
  (do ((i 1 (+ i 1)))
    ((> i n))
    (cond ((and (= (modulo i x) 0)
                (= (modulo i y) 0))
           (print "FizzBuzz"))
          ((= (modulo i y) 0)
           (print "Buzz"))
          ((= (modulo i x) 0)
           (print "Fizz"))
          ( else (print i)))))
