(letrec* ((ah (read))
          (a1 (read))
          (am (read))
          (a2 (read))
          (as (read))
          (bh (read))
          (b1 (read))
          (bm (read))
          (b2 (read))
          (bs (read))
          (asecond (+ (* 3600 ah) (* 60 am) as))
          (bsecond (+ (* 3600 bh) (* 60 bm) bs)))
  (if (> asecond bsecond)
    (print (- bsecond asecond -86400))
    (print (- bsecond asecond))))
