(define a (read))
(define b (read))
(define (iter count a b)
  (if (< count 1000)
    (begin (display (quotient a b))
           (iter (+ count 1) (* 10 (modulo a b)) b))
    (newline)))
(display (quotient a b))
(display ".")
(iter 0 (* 10(modulo a b)) b)
