(define dp-vector (make-vector 50001 0))
(vector-set! dp-vector 1 1)
(vector-set! dp-vector 2 1)
(vector-set! dp-vector 3 2)
(define (iter count)
  (if (< count 50001)
    (begin (vector-set! dp-vector count (modulo (+ (vector-ref dp-vector (- count 1))
                                                   (vector-ref dp-vector (- count 3))) 1000000009))
           (iter (+ count 1)))))
(iter 4)
(print (vector-ref dp-vector (read)))
