(define Persepolis-home (read))
(define Esteghlal-away (read))
(define Esteghlal-home (read))
(define Persepolis-away (read))
(cond ((<
         (+ Persepolis-home Persepolis-away)
         (+ Esteghlal-home Esteghlal-away))
       (display "Esteghlal\n"))
      ((> (+ Persepolis-home Persepolis-away)
          (+ Esteghlal-home Esteghlal-away))
       (display "Persepolis\n"))
      ((> Persepolis-home Esteghlal-home)
       (display "Esteghlal\n"))
      ((< Persepolis-home Esteghlal-home)
       (display "Persepolis\n"))
      (else (display "Penalty\n")))
