(letrec* ((a (* 3 (read)))
          (b (* 2 (read)))
          (c (read))
          (d (* 3 (read)))
          (e (* 2 (read)))
          (f (read))
          (A (+ a b c))
          (B (+ d e f)))
     (if (> A B)
      (print "A")
      (if (< A B)
       (print "B")
       (print "T"))))
