(define dp-8 (make-vector 8))
(define dp-7 (make-vector 8))
(define dp-6 (make-vector 8))
(define dp-5 (make-vector 8))
(define dp-4 (make-vector 8))
(define dp-3 (make-vector 8))
(define dp-2 (make-vector 8))
