(define a.x (read))
(define a.y (read))
(define a.z (read))
(define c.x (read))
(define c.y (read))
(define c.z (read))
(display (- c.x a.z))
(display " ")
(display (quotient c.y a.y))
(display " ")
(display (- c.z a.x))
(newline)
