(define n (read))
(cond ((= (modulo n 8) 1) (display "1\n"))
      ((= (modulo n 8) 5) (display "5\n"))
      ((= (modulo n 8) 3) (display "3\n"))
      ((= (modulo n 8) 7) (display "3\n"))
      ((= (modulo n 8) 2) (display "2\n"))
      ((= (modulo n 8) 0) (display "2\n"))
      ((= (modulo n 8) 4) (display "4\n"))
      ((= (modulo n 8) 6) (display "4\n")))
