(define (sum-digit n)
    (do ((lst n (quotient lst 10))
         (acc 0 acc))
        ((= lst 0) acc)
        (set! acc (+ acc (modulo lst 10)))))
(do ((n 0 (+ n 1))
     (lst (read) lst))
  ((< lst 10) (print n) (if (= (modulo lst 3) 0)
                          (print "YES")
                          (print "NO")))
  (set! lst (sum-digit lst)))
