(define dp-vec (make-vector 251 0))
(vector-set! dp-vec 0 1)
(vector-set! dp-vec 1 1)
(vector-set! dp-vec 2 3)
(define (dp n)
  (if (< n 251)
    (begin (vector-set! dp-vec n (+ (vector-ref dp-vec (- n 1))
                                    (* 2 (vector-ref dp-vec (- n 2)))))
           (dp (+ n 1)))))
(dp 3)
(define (iter)
  (define n (read))
  (if (number? n)
    (begin (print (vector-ref dp-vec n))
           (iter))))
(iter)
