(define n (read))
(define (solve n)
 (if (> n 0)
  (let ((a (read))
        (b (read)))
   (print (+ a b) " " (* a b))
   (solve (- n 1)))))
(define (iter n)
 (if (> n 0)
  (begin (solve (read))
         (iter (- n 1)))))
(iter n)
