(import (chicken io))
(define is-vowel? (lambda (x)
                    (cond ((equal? x #\a) 1)
                          ((equal? x #\e) 1)
                          ((equal? x #\i) 1)
                          ((equal? x #\o) 1)
                          ((equal? x #\u) 1)
                          (else 0))))

(define n (string->number(read-line)))
(define (iter n acc)
  (if (> n 0)
    (iter (- n 1) (+ acc (is-vowel? (read-char))))
    acc))
(print (iter n 0))
