(define n (read))
(define w (read))
(define h (read))
(define l (read))
(define room (* (quotient w l)
                (quotient h l)))
(cond ((< room n)
       (display room)(newline))
      (else (display n)(newline)))
