(do ((n (read) (- n 1)))
 ((= n 0))
 (do ((t (read) (- t 1))
      (minv 1000000 minv)
      (maxv -1000000 maxv))
   ((= t 0) (print minv " " maxv))
   (let ((i (read)))
     (set! minv (min minv i))
     (set! maxv (max maxv i)))))
