(define (class)
  (define name (read))
  (define age (read))
  (define mess (read))
  (if (not (= age 0))
    (begin (if (> age 17)
             (print name " Senior")
             (if (>= mess 80)
              (print name " Senior")
              (print name " Junior")))
           (class))))
(class)
