(let ((a (read))
      (c (read))
      (e (read))
      (x (read))
      (y (read))
      (z (read)))
  (cond ((and (>= x a) (>= y c) (>= z e)) (print "A"))
        ((and (>= x (/ a 2)) (>= y c) (>= z e)) (print "B"))
        ((and (>= y c) (>= z e)) (print "C"))
        ((and (>= y (/ c 2)) (>= z e)) (print "D"))
        (else (print "E"))))
