(import (chicken string))
(import (chicken io))
(define (words string) (string-split string " " #t))
(define (class)
  (define read-string (words (read-line)))
  (if (not(eq? read-string '()))
    (let ((age (string->number (list-ref read-string 1)))
          ( name (list-ref read-string 0))
          (mess (string->number (list-ref read-string 2))))
         (if (not (= age 0))
           (begin (if (> age 17)
                    (print name " Senior")
                    (if (>= mess 80)
                     (print name " Senior")
                     (print name " Junior")))
                  (class))))))
(class)
