(do ((n 9 (- n 1))
     (hack? #f hack?)
     (acc 0 acc))
  ((= n 0)
   (cond (hack? (print "hacker"))
         ((< acc 100) (print "none"))
         (else (print "draw"))))
  (let ((point (read)))
       (cond ((and (>= n 8) (> point 100)) (set! hack? #t))
             ((and (>= n 6) (> point 200)) (set! hack? #t))
             ((and (>= n 4) (> point 300)) (set! hack? #t))
             ((and (>= n 2) (> point 400)) (set! hack? #t))
             ((and (= n 1) (> point 500)) (set! hack? #t)))
       (set! acc (+ acc point))))
