(let ((a (read))
      (b (read))
      (c (read))
      (d (read))
      (e (read))
      (f (read)))
  (if (> (expt (+ c f) 2) (+ (expt (- a d) 2) (expt (- b e) 2)))
    (print "YES")
    (print "NO")))
