(let ((a (read))
      (b (read))
      (c (read)))
  (do ((n (read) (- n 1))
       (maxv 0 maxv))
    ((= n 0) (print maxv))
    (set! maxv (max maxv (+ (* a (read)) (* b (read)) (* c (read))
                            (* a (read)) (* b (read)) (* c (read))
                            (* a (read)) (* b (read)) (* c (read)))))))
