(display " _________\n")
(display " \\_     _/\n")
(display "   \\   /\n")
(display "    | |\n")
(display "   /   \\\n")
(display "  /     \\\n")
(display " |       |\n")
(display "/---------\\\n")
(display "| \\-/ \\-/ |\n")
(display "\\---------/\n")
(display " \\_______/\n")
