(import (chicken io))
(define (decode c)
  (- (char->integer c)
     (char->integer #\A)
     -1))
(define encode (string->list (read-line)))
(do ((result `(,(car encode)) result)
     (leader 0 leader))
  ((= leader (- (length encode) 1))
   (print (list->string (reverse result))))
  (define index (decode (car result)))
  (set! result
        (cons (list-ref encode (+ index leader))
              result))
  (set! leader (+ leader index)))
