(define count (read))
(define (iter f n)
  (if (> n 0)
    (begin (f n)
           (newline)
           (iter f (- n 1)))))
(define (print-stars n)
  (if (> n 0)
    (begin (display "*")
           (print-stars (- n 1)))))
(iter print-stars count)
