(define w (read))
(define (iter n)
  (if (> n 0)
    (begin (print-space (- w n))
           (print-star n)
           (iter (- n 1)))))
(define (print-star n)
  (if (> n 0)
    (begin (display "*") (print-star (- n 1)))
    (newline)))
(define (print-space n)
  (if (> n 0)
    (begin (display " ") (print-space (- n 1)))))

(iter w)
