(define (space-print n)
  (if (> n 0)
    (begin (display " ")
           (space-print (- n 1)))))
(define (star-print n)
  (if (> n 0)
    (begin (display "*")
           (star-print (- n 1)))))

(define height (read))
(define (iter n)
  (if (> n 0)
    (begin (star-print (- n 1))
           (space-print (+ (* 2 (- height n)) 2))
           (star-print (- n 1))
           (display "\n")
           (iter (- n 1)))))
(define height-1 (- height 1))
(define (riter n)
  (if (> n 0)
    (begin (star-print (- height n))
           (space-print (+ (* 2 (- n 1)) 2))
           (star-print (- height n))
           (display "\n")
           (riter (- n 1)))))
(riter height-1)
(star-print (* 2 height))
(newline)
(iter height)
