(define num1 (read))
(define num2 (read))
(define num3 (read))
(define num4 (read))
(define num5 (read))
(define (square n) (* n n))
(display (modulo (+ (square num1)
            (square num2)
            (square num3)
            (square num4)
            (square num5)
           ) 10))
(newline)
