(do ((n (read) (- n 1))
     (acc 0 acc))
  ((= n 0) (print acc))
  (let ((a (read))
        (b (read))
        (c (read)))
    (cond ((= a b c) (set! acc (max acc (+ 10000 (* a 1000)))))
          ((= a b) (set! acc (max acc (+ 1000 (* a 100)))))
          ((= a c) (set! acc (max acc (+ 1000 (* a 100)))))
          ((= b c) (set! acc (max acc (+ 1000 (* b 100)))))
          (else (set! acc (max acc (* 100 (max a b c))))))))
