(define (sol)
  (define n (+ (read) (read) (read) (read)))
  (cond ((= n 0) (print "D"))
        ((= n 1) (print "C"))
        ((= n 2) (print "B"))
        ((= n 3) (print "A"))
        ((= n 4) (print "E"))))
(sol)
(sol)
(sol)
