(define (print-star n)
  (do ((i 0 (+ i 1)))
    ((= i n) (newline))
    (display "*")))
(let ((n (read)))
  (do ((i 1 (+ i 1)))
    ((> i n))
    (print-star i))
  (do ((i (- n 1) (- i 1)))
    ((< i 1))
    (print-star i)))
