(letrec* ((t1 (read))
          (m1 (read))
          (t2 (read))
          (m2 (read))
          (during (+ (* (- t2 t1)60)
                     (- m2 m1))))
  (if (>= during 0)
    (print during " " (quotient during 30))
    (print (+ 1440 during) " " (quotient (+ 1440 during) 30))))
