(define (koi-bread n acc)
  (if (> n 0)
      (let ((a (read))
            (b (read)))
        (if (<= a b)
          (koi-bread (- n 1) (cons b acc))
          (koi-bread (- n 1) acc)))
      (if (eqv? '() acc)
        (print -1)
        (print (apply min acc)))))
(koi-bread (read) '())
