(define (iter n)
  (define (useble-pw password-lenth)
    (cond ((and (>= password-lenth 6) (<= password-lenth 9))
           (display "yes")(newline))
          (else (display "no")(newline))))
  (define (password-lenth password)
   (string-length (cond ((symbol? password)
                         (symbol->string password))
                        (else (number->string password)))))
  (if (> n 0)
      (begin (useble-pw (password-lenth (read)))
             (iter (- n 1)))))
(iter (read))
