(do ((n (read) (- n 1))
     (win 0 win))
  ((= n 0) (print win))
  (letrec* ((a (read))
            (d (read))
            (g (read))
            (score (* a (+ d g))))
    (set! win (max (if (= a (+ d g))
                     (* 2 score)
                     score) win))))
