(define n1 (read))
(define n2 (read))
(define n3 (read))
(define n4 (read))
(define n5 (read))
(define n6 (read))
(define n7 (read))
(define n8 (read))
(define n9 (read))
(define max-val (max n1 n2 n3 n4 n5 n6 n7 n8 n9))
(display max-val)
(newline)
(display (cond ((= n1 max-val) 1)
               ((= n2 max-val) 2)
               ((= n3 max-val) 3)
               ((= n4 max-val) 4)
               ((= n5 max-val) 5)
               ((= n6 max-val) 6)
               ((= n7 max-val) 7)
               ((= n8 max-val) 8)
               ((= n9 max-val) 9)))
(newline)
