(let ((n (read))
      (p (read)))
  (cond ((>= n 20) (if (>= p 8000)
                     (print (* (/ p 100) 75))
                     (if (>= p 2000)
                       (print (- p 2000))
                       (print 0))))
        ((>= n 15) (if (>= p 20000)
                     (print (* (/ p 100) 90))
                     (if (>= p 2000)
                       (print (- p 2000))
                       (print 0))))
        ((>= n 10) (if (>= p 5000)
                     (print (* (/ p 100) 90))
                     (if (>= p 500)
                       (print (- p 500))
                       (print 0))))
        ((>= n 5) (if (>= p 500)
                    (print (- p 500))
                    (print 0)))
        (else (print p))))
