(do ((n 7 (- n 1))
     (acc 0 acc)
     (minv 101 minv))
  ((= n 0) (if (= 0 acc)
               (print -1)
               (begin (print acc)
                      (print minv))))
  (let ((i (read)))
    (if (odd? i)
        (begin (set! acc (+ acc i))
               (if (< i minv)
                 (set! minv i))))))
