(define a (read))
(define b (read))
(define b1 (modulo b 10))
(define b2 (modulo (quotient b 10) 10))
(define b3 (quotient b 100))
(display (* a b1))
(newline)
(display (* a b2))
(newline)
(display (* a b3))
(newline)
(display (* a b))
(newline)
