(do ((t (read) (- t 1)))
  ((= t 0))
  (letrec* ((a1 (read))
            (b1 (read))
            (c1 (read))
            (a (>= a1 10))
            (b (>= b1 10))
            (c (>= c1 10)))
    (print a1 " " b1 " " c1)
    (if (and a b c)
      (begin (print "triple-double")
             (newline))
      (if (or (and a b) (and b c) (and a c))
        (begin (print "double-double")
             (newline))
        (if (or a b c)
          (begin (print "double")
             (newline))
          (begin (print "zilch")
             (newline)))))))
