(define (iter)
  (if (and (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read)))
           (not (= 9 (read))))
      (display "S\n")
      (display "F\n")))
(iter)
