(do ((t (read) (- t 1)))
    ((= t 0))
    (let ((a (read))
          (b (read))
          (n (read)))
      (print "Data set: " a " " b " " n)
      (do ((n n (- n 1))
           (a a a)
           (b b b))
          ((= n 0) (print (max a b) " " (min a b))
                   (newline))
          (if (> a b)
            (set! a (quotient a 2))
            (set! b (quotient b 2))))))
