(define (iter count)
  (if (and (not (eof-object? (read)))
           (not (eof-object? (read)))
           (not (eof-object? (read)))
           (not (eof-object? (read)))
           (not (eof-object? (read))))
    (iter (+ count 1))
    (display count)))
(iter 0)
(newline)
