(define n (read))
(define (iter n)
  (if (> n 0)
    (begin (population)
           (iter (- n 1)))))
(define (population)
  (define p (read))
  (define t (read))
  (print (+ p (quotient t 4) (- (quotient t 7)))))
(iter n)
