(import (chicken flonum))
(define (iter n)
  (define (format-print)
    (define value (fpround (* 1.0 (read) (read) (read))))
    (display "$")
    (display (right-pad value 2))
    (display "\n"))
  (if (> n 0)
    (begin (format-print)
           (iter (- n 1)))))
(iter (read))
