(import (chicken foreign))
(foreign-declare "#include<stdio.h>")
(do ((t (read) (- t 1)))
  ((= t 0))
  (let ((area (read))
        (base (read)))
    ((foreign-lambda* void ((float f))
        "printf(\"The height of the triangle is %.2f units\\n\", f);")
     (exact->inexact (/ (* area 2) base)))))
