(import (chicken io))
(let ((input (string->list (read-line))))
  (do ((iter input (cdr iter))
       (a 0 a)
       (b 0 b))
    ((null? iter)
     (print a " : " b))
    (if (equal? (car iter) #\A)
      (set! a (+ a 1))
      (set! b (+ b 1)))))
