(define (hoorra n)
  (let ((mod7 (modulo n 7))
        (mod11 (modulo n 11)))
    (cond ((= (+ mod7 mod11) 0) (print "Wiwat!"))
          ((= mod7 0) (print "Hurra!"))
          ((= mod11 0) (print "Super!"))
          (else (print n)))))
(define (iter n acc)
  (if (>= n acc)
    (begin (hoorra acc)
           (iter n (+ acc 1)))))
(iter (read) 1)
