(let ((a (read))
      (b (read))
      (c (read))
      (d (read))
      (e (read)))
  (if (= (* 4 (min a b c d)) (* 4 (max a b c d)))
    (print 1)
    (if (= (+ e a b c d) (* 4 (max a b c d)))
      (print 1)
      (print 0))))
