(import (chicken sort))
(import (chicken io))
(import (chicken string))
(define (make-list)
  (sort (map string->number (string-split (string-chomp (read-line)))) <))
(let ((n (read)))
  (read-line)
  (do ((n n (- n 1)))
    ((= n 0))
    (print (list-ref (make-list) 7))))
