(define n (read))
(define (print-v n)
  (cond ((> n 0)
         (display "V")
         (print-v (- n 1)))))
(define (print-I n)
  (cond ((> n 0)
         (display "I")
         (print-I (- n 1)))))
(begin (print-v (quotient n 5))
       (print-I (modulo n 5))
       (newline))
