(define (sum-bin)
  (print (number->string (+ (string->number (number->string (read) 10) 2)
                            (string->number (number->string (read) 10) 2))
                         2)))
(define (iter count)
  (if (> count 0)
    (begin (sum-bin)
           (iter (- count 1)))))
(iter (read))
