(define (iter acc)
  (define char (read-char))
  (if (eqv? char #\:)
      (+ 2 acc)
      (if (eqv? char #\_)
        (iter (+ acc 6))
        (iter (+ acc 1)))))
(read-char)
(display (iter 2))
(newline)
