(define n (read))
(define (nine-nine count)
  (cond ((<= count 9)
         (display n)
         (display " * ")
         (display count)
         (display " = ")
         (display (* count n))
         (newline)
         (nine-nine (+ count 1)))))
(nine-nine 1)
