(import (chicken sort))
(define (list-print lst)
  (do ((lst lst (cdr lst)))
    ((null? lst))
    (print (car lst))))
(do ((n (read) (- n 1))
     (acc '() acc))
  ((= n 0)
   (list-print (sort! acc (lambda (x y) (<= x y)))))
  (set! acc (cons (read) acc)))
