(case (read)
   ('A+ (display "4.3\n"))
   ('A0 (display "4.0\n"))
   ('A- (display "3.7\n"))
   ('B+ (display "3.3\n"))
   ('B0 (display "3.0\n"))
   ('B- (display "2.7\n"))
   ('C+ (display "2.3\n"))
   ('C0 (display "2.0\n"))
   ('C- (display "1.7\n"))
   ('D+ (display "1.3\n"))
   ('D0 (display "1.0\n"))
   ('D- (display "0.7\n"))
   ('F (display "0.0\n")))
