(define (live-room a b)
  (cond ((= a 0) b)
        ((= b 1) 1)
        (else (+ (live-room a (- b 1))
                 (live-room (- a 1) b)))))
(define test-case (read))
(define (iter n)
  (cond ((>= n 1)
         (display (live-room (read) (read)))
         (newline)
         (iter (- n 1)))))
(iter test-case)
