(import (chicken bitwise))
(define (even x) (bitwise-xor (quotient x 2) 6))
(define (odd x) (bitwise-xor (* x 2) 6))
(do ((x (read) x)
     (n (read) (- n 1)))
  ((<= n 0) (print x))
  (if (even? x)
    (set! x (even x))
    (set! x (odd x))))
