(do ((c (read-char) (read-char))
     (m #f m)
     (o #f o)
     (b #f b)
     (i #f i)
     (s #f s))
  ((eof-object? c)
   (if (and m o b i s)
     (print "YES")
     (print "NO")))
  (case c
    ((#\M) (set! m #t))
    ((#\O) (set! o #t))
    ((#\B) (set! b #t))
    ((#\I) (set! i #t))
    ((#\S) (set! s #t))))
