(do ((n (read) (- n 1))
     (acc 0 acc))
  ((= n 0) (print acc))
  (let ((a (symbol->string (read))))
    (cond ((equal? "Poblano" a) (set! acc (+ acc 1500)))
          ((equal? "Mirasol" a) (set! acc (+ acc 6000)))
          ((equal? "Serrano" a) (set! acc (+ acc 15500)))
          ((equal? "Cayenne" a) (set! acc (+ acc 40000)))
          ((equal? "Thai" a) (set! acc (+ acc 75000)))
          ((equal? "Habanero" a) (set! acc (+ acc 125000))))))
