(let ((n (read))
      (k (read)))
  (let ((avec (make-vector (+ n 1)  1001)))
    (do ((i 1 (+ i 1)))
      ((= i (+ n 1))
       (print (* k (apply min (vector->list avec)))))
      (let ((a (read)))
        (vector-set! avec (- i 1) (+ a (vector-ref avec (- i 1))))
        (if (< i n)(vector-set! avec i a))))))
