(import (chicken io))
(let ((str (read-line)))
  (cond ((equal? "fdsajkl;" str) (print "in-out"))
        ((equal? "jkl;fdsa" str) (print "in-out"))
        ((equal? "asdf;lkj" str) (print "out-in"))
        ((equal? ";lkjasdf" str) (print "out-in"))
        ((equal? "asdfjkl;" str) (print "stairs"))
        ((equal? ";lkjfdsa" str) (print "reverse"))
        (else (print "molu"))))
