(letrec* ((n (read))
          (m (read))
          (k (read))
          (team (min (quotient n 2) m))
          (remind (- k (- (+ n m) (* 3 team)))))
  (if (> remind 0)
    (let ((remind-team (ceiling (/ remind 3))))
      (print (- team remind-team)))
    (print team)))
