(define a1 (read))
(define a2 (read))
(define a3 (read))
(define a4 (read))
(define a5 (read))
(define a6 (read))
(define a7 (read))
(define a8 (read))

(cond
  ((and
    (= a1 1)
    (= a2 2)
    (= a3 3)
    (= a4 4)
    (= a5 5)
    (= a6 6)
    (= a7 7)
    (= a8 8))
   (display "ascending")
   (newline))
  ((and
    (= a1 8)
    (= a2 7)
    (= a3 6)
    (= a4 5)
    (= a5 4)
    (= a6 3)
    (= a7 2)
    (= a8 1))
   (display "descending")
   (newline))
  (else (display "mixed")(newline)))
