(let ((a (+ (read) (read) (read) (read)))
      (b (+ (read) (read) (read) (read)))
      (c (+ (read) (read) (read) (read)))
      (d (+ (read) (read) (read) (read)))
      (e (+ (read) (read) (read) (read))))
  (let ((score (max a b c d e)))
    (cond ((= score a) (print 1 " " score))
          ((= score b) (print 2 " " score))
          ((= score c) (print 3 " " score))
          ((= score d) (print 4 " " score))
          ((= score e) (print 5 " " score)))))
