(let ((a (read))
      (b (read))
      (c (read))
      (d (read)))
  (let ((minv (min a b c))
        (maxv (max a b c)))
    (cond ((< d minv) (print (* d (- (+ a b c) minv maxv))))
          ((> d maxv) (print (* minv maxv)))
          (else (print (* minv (max (- (+ a b c) minv maxv) d)))))))
