(define king (read))
(define queen (read))
(define lock (read))
(define cardinal (read))
(define knight (read))
(define 폰 (read))

(display (- 1 king))
(display " ")
(display (- 1 queen))
(display " ")
(display (- 2 lock))
(display " ")
(display (- 2 cardinal))
(display " ")
(display (- 2 knight))
(display " ")
(display (- 8 폰))
(newline)
