(define (iter)
 (define a (expt (read) 2))
 (define b (expt (read) 2))
 (define c (expt (read) 2))
 (define (ortho-triangle?)
  (if (= (+ a b c) (* 2 (max a b c)))
    (display "right\n")
    (display "wrong\n")))
 (if (not (= a 0))
   (begin (ortho-triangle?)
          (iter))))
(iter)
