(import (chicken io))
(define (print-num n)
  (print n ". " (read-line)))
(define (iter count)
  (if (<= count n)
    (begin (print-num count)
           (iter (+ count 1)))))
(define n (string->number(read-line)))
(iter 1)
