(define n (read))
(define (cmp a b c)
 (let ((maxv (max a b c))
       (minv (min a b c)))
  (if (or (and (= maxv a) (= minv c))
          (and (= minv a) (= maxv c)))
   (print "Ordered")
   (print "Unordered"))))
(print "Gnomes:")
(define (iter n)
 (if (> n 0)
  (begin (cmp (read) (read) (read))
         (iter (- n 1)))))
(iter n)
