(define (class-triangle a b c)
  (if (>= (* 2 (max a b c)) (+  a b c))
    (print "Invalid")
    (if (= a b c)
      (print "Equilateral")
      (if (or (= a b) (= b c) (= a c))
        (print "Isosceles")
        (print "Scalene")))))
(define (iter)
 (define a (read))
 (define b (read))
 (define c (read))
 (if (not (= a b c 0))
   (begin (class-triangle a b c)
          (iter))))
(iter)
