(define (iter)
  (define n (read))
  (define m (read))
  (if (not (= n m 0))
    (cond ((= (modulo n m) 0)
           (print "multiple")
           (iter))
          ((= (modulo m n) 0)
           (print "factor")
           (iter))
          (else
            (print "neither")
            (iter)))))
(iter)
