(display"     /~\\\n")
(display"    ( oo|\n")
(display"    _\\=/_\n")
(display"   /  _  \\\n")
(display"  //|/.\\|\\\\\n")
(display" ||  \\ /  ||\n")
(display"============\n")
(display"|          |\n")
(display"|          |\n")
(display"|          |\n")
