(import (chicken io))
(define (dedupe acc)
  (define c (read-char))
  (if (and (char-alphabetic? c) (not (eq? c (car acc))))
    (dedupe (cons c acc))
    (if (char-alphabetic? c)
      (dedupe acc)
      (print (list->string (reverse acc))))))
(define (iter n)
  (if (> n 0)
    (begin (dedupe `(,(read-char)))
           (iter (- n 1)))))
(iter (string->number(read-line)))
