(define (time-check)
  (let* ((sh (read))
         (sm (read))
         (ss (read))
         (th (read))
         (tm (read))
         (ts (read))
         (rh (- th sh))
         (rm (- tm sm))
         (rs (- ts ss)))
    (if (< rs 0)
      (begin (set! rs (+ 60 rs))
             (set! rm (- rm 1))))
    (if (< rm 0)
      (begin (set! rm (+ 60 rm))
             (set! rh (- rh 1))))
    (print rh " " rm " " rs)))

(time-check)
(time-check)
(time-check)
