(let ((a (read))
      (b (read)))
 (cond ((<= b a) (print "Congratulations, you are within the speed limit!"))
       ((<= b (+ a 20)) (print "You are speeding and your fine is $100."))
       ((<= b (+ a 30)) (print "You are speeding and your fine is $270."))
       (else (print "You are speeding and your fine is $500."))))
