(define s1 (read))
(define s2 (read))
(define s3 (read))
(define s4 (read))
(cond ((and (< s1 s2)
            (< s2 s3)
            (< s3 s4))
       (display "Fish Rising\n"))
      ((and (> s1 s2)
            (> s2 s3)
            (> s3 s4))
       (display "Fish Diving\n"))
      ((and (= s1 s2)
            (= s2 s3)
            (= s3 s4))
       (display "Fish At Constant Depth\n"))
      (else (display "No Fish\n")))
