(display "The 1-3-sum is ")
(display (+ (* 9 1)
            (* 7 3)
            (* 8 1)
            (* 0 3)
            (* 9 1)
            (* 2 3)
            (* 1 1)
            (* 4 3)
            (* 1 1)
            (* 8 3)
            (* (read) 1)
            (* (read) 3)
            (* (read) 1)))
(newline)
