(define a (read))
(define b (read))
(define c (read))
(cond ((and (not (= a (max a b c)))
            (not (= a (min a b c))))
       (display a))
      ((and (not (= b (max a b c)))
            (not (= b (min a b c))))
       (display b))
      (else (display c)))
(newline)
