(import (chicken io))
(do ((x (read-line) (read-line)))
  ((eof-object? x))
  ((lambda (a)
     (cond ((equal? "CU" a) (print "see you"))
           ((equal? ":-)" a) (print "I’m happy"))
           ((equal? ":-(" a) (print "I’m unhappy"))
           ((equal? ";-)" a) (print "wink"))
           ((equal? ":-P" a) (print "stick out my tongue"))
           ((equal? "(~.~)" a) (print "sleepy"))
           ((equal? "TA" a) (print "totally awesome"))
           ((equal? "CCC" a) (print "Canadian Computing Competition"))
           ((equal? "CUZ" a) (print "because"))
           ((equal? "TY" a) (print "thank-you"))
           ((equal? "YW" a) (print "you’re welcome"))
           ((equal? "TTYL" a) (print "talk to you later"))
           (else (print x))))
   x))
