(let ((n (read))
      (r (expt (read) 2))
      (x (read))
      (y (read)))
  (do ((i n (- i 1))
       (acc 0 acc))
    ((= i 0) (print acc))
    (if (< r (+ (expt (- (read) x) 2) (expt (- (read) y) 2)))
      (set! acc (+ acc 1)))))
