(let ((x (* 1000 (read)))
      (k (* 1000 (read))))
  (let ((small (* (/ 7 4) k))
        (middle (* (/ 7 2 ) k))
        (big (* 7 k)))
    (cond ((<= big x) (print big))
          ((<= middle x) (print middle))
          ((<= small x) (print small))
          (else (print 0)))))
