(let ((a (read))
      (b (read))
      (c (read)))
 (if (= (max a b c) (min a b c))
  (print 2)
  (if (= (* 2 (expt (max a b c) 2))
         (+ (expt a 2) (expt b 2) (expt c 2)))
      (print 1)
      (print 0))))
