(define dp-vector (make-vector 12 1))
(vector-set! dp-vector 1 1)
(vector-set! dp-vector 2 2)
(vector-set! dp-vector 3 4)
(define (init n)
  (if (< n 12)
      (begin (vector-set! dp-vector n (+ (vector-ref dp-vector (- n 3))
                                         (vector-ref dp-vector (- n 2))
                                         (vector-ref dp-vector (- n 1))))
             (init (+ n 1)))))

(define (iter n)
  (if (> n 0)
    (begin (print (vector-ref dp-vector (read)))
           (iter (- n 1)))))
(init 4)
(iter (read))
