(define dp-vector (make-vector 101 0))
(vector-set! dp-vector 1 1)
(vector-set! dp-vector 2 1)
(vector-set! dp-vector 3 1)
(define (init n)
  (if (< n 101)
    (begin (vector-set! dp-vector n (+ (vector-ref dp-vector (- n 2))
                                       (vector-ref dp-vector (- n 3))))
           (init (+ n 1)))))
(init 4)
(define (print-ans)
  (print (vector-ref dp-vector (read))))
(define (iter n)
  (if (> n 0)
    (begin (print-ans)
           (iter (- n 1)))))
(iter (read))
