(do ((n (read) (- n 1))
     (q1 0 q1)
     (q2 0 q2)
     (q3 0 q3)
     (q4 0 q4)
     (axis 0 axis))
  ((= n 0) (print "Q1: " q1)
           (print "Q2: " q2)
           (print "Q3: " q3)
           (print "Q4: " q4)
           (print "AXIS: " axis))
  (let ((x (read))
        (y (read)))
    (cond ((or (= x 0) (= y 0)) (set! axis (+ axis 1)))
          ((and (> x 0) (> y 0)) (set! q1 (+ q1 1)))
          ((and (< x 0) (> y 0)) (set! q2 (+ q2 1)))
          ((and (< x 0) (< y 0)) (set! q3 (+ q3 1)))
          ((and (> x 0) (< y 0)) (set! q4 (+ q4 1))))))
