(define (find-quadr x y)
  (cond ((= x 0) (print "AXIS"))
        ((= y 0) (print "AXIS"))
        ((and (> x 0) (> y 0)) (print "Q1"))
        ((and (< x 0) (> y 0)) (print "Q2"))
        ((and (< x 0) (< y 0)) (print "Q3"))
        ((and (> x 0) (< y 0)) (print "Q4"))))
(define (iter)
  (define x (read))
  (define y (read))
  (if (= x y 0)
    (print "AXIS")
    (begin (find-quadr x y)
           (iter))))
(iter)
