(import (chicken io))
(import (chicken string))
(import (chicken foreign))
(foreign-declare "#include<stdio.h>")
(define fprint (foreign-lambda* void ((float f))
                                "printf(\"%.1f\",f);"))
(do ((test (map string->number (string-split (read-line) " "))
           (map string->number (string-split (read-line) " ")))
     (t 1 (+ t 1)))
  ((= (car test) 0))
  (display "Case ")
  (display t)
  (display ": ")
  (letrec* ((seq (cdr test))
            (l (length seq)))
    (if (even? l)
      (fprint (exact->inexact (/ (+ (list-ref seq (quotient l 2))
                                    (list-ref seq (- (quotient l 2) 1))) 2)))
      (fprint (list-ref seq (quotient l 2)))))
  (newline))
