(define (wl-read)
  (define n (char->integer (read-char)))
  (if (= n 76) 1 0))
(let ((a  (quotient (+ (wl-read) (wl-read) (wl-read) (wl-read) (wl-read) (wl-read))
                    2)))
  (cond ((= a 0) (print 1))
        ((= a 1) (print 2))
        ((= a 2) (print 3))
        (else (print -1))))
